Book appointment and add to owners Calendar
kalle-app/kalle pull request #105
Opened 2021-01-07 15:38 UTC by rohansaw

Closes: #101

- Booked Appointments will be added to DB
-  Customer has an overview of booked appointments for every meeting
- Added Caldav query to create events
- Creating the according event when an event is booked

2021-01-10 09:00 UTC, rohansaw commented
Currently pipeline is not running to as the test ist not passing in the ci. I really don't understand why, locally its working as expected. I tried debugging it but cannot find the mistake. Maybe someone could take a look at this please

2021-01-11 08:31 UTC, Skn0tt requested changes

2021-01-11 08:31 UTC, Skn0tt commented on app/appointments/mutations/bookAppointment.ts
> +  const calendar = await db.connectedCalendar.findFirst({
Could the queries for `meetingOwner` and `calendar` be combined with the initial `meeting` query above? Prisma has an option called `include` that should allow this.

2021-01-11 08:31 UTC, Skn0tt commented on app/appointments/mutations/bookAppointment.ts
> +  if (!meetingOwner) return null
In L21, the code throws when its preconditions aren't met. Is there a reason for this to return null instead?

2021-01-11 08:31 UTC, Skn0tt commented on app/appointments/mutations/bookAppointment.ts
> +  if (!calendar) return null
See return-null-comment above.

2021-01-11 08:31 UTC, Skn0tt commented on app/appointments/mutations/bookAppointment.ts
> +  console.log(bookingDetails.date)
```suggestion
```

2021-01-11 08:31 UTC, Skn0tt commented on app/appointments/mutations/bookAppointment.ts
> +      auth: { username: calendar.username, password, digest: true },
`digest` shouldn't be hard-coded. We should add two new types à la `CalDav/Basic` and `CalDav/Digest` to store what authentication scheme should be used.

2021-01-11 08:31 UTC, Skn0tt commented on app/appointments/mutations/bookAppointment.ts
> +      name: meeting.name + "with" + bookingDetails.inviteeEmail,
Doesn't this miss some spaces? Using a template string instead would make this more obious.
```suggestion
      name: `${meeting.name} with ${bookingDetails.inviteeEmail}`,
```

2021-01-11 08:31 UTC, Skn0tt commented on app/appointments/mutations/bookAppointment.ts
> +import moment from "moment"
Moment JS is [considered a legacy project](https://momentjs.com/docs/#/-project-status/), and alternatives should be used. I've had good experiences with [`date-fns`](https://date-fns.org), maybe we could use that instead.

2021-01-11 08:31 UTC, Skn0tt commented on app/appointments/pages/schedule/[username]/[slug].tsx
> +    bookAppointment({
This call isn't awaited, so the next call (`sendConfirmationMail`) is made immediately afterwards. If bookAppointment fails, the mail is still sent. Is that desirable?

Apart from that, I don't think that the client should do both of these calls.
We should add a new mutation instead that both books the appointment and sends to confirmation mail, as that'd save the client the overhead of an additional round trip.

2021-01-11 08:31 UTC, Skn0tt commented on app/caldav/index.spec.ts
> +import moment from "moment"
See above comment on `moment`.

2021-01-11 08:31 UTC, Skn0tt commented on app/meetings/pages/meeting/bookings/[meetingId].tsx
> +    return <Skeleton count={10} />
Could we extract `<Skeleton count={10} />` into another variable called `fallback`?

2021-01-11 08:31 UTC, Skn0tt commented on app/meetings/pages/meeting/bookings/[meetingId].tsx
> +  console.log(bookings)
```suggestion
```

2021-01-11 08:31 UTC, Skn0tt commented on app/meetings/pages/meeting/bookings/[meetingId].tsx
> +  console.log(bookings)
There's a lot of console.log-statements littered over this PR. Don't you go over your code before you request a review?

2021-01-11 08:31 UTC, Skn0tt commented on app/meetings/queries/getBookings.ts
> +  if (!ctx.session?.userId) return null
```suggestion
ctx.session.authorize()
```

2021-01-11 08:31 UTC, Skn0tt commented on app/meetings/queries/getBookings.ts
> +  console.log(meeting)
```suggestion
```

2021-01-11 08:31 UTC, Skn0tt commented on app/meetings/queries/getBookings.ts
> +  const bookings = await db.booking.findMany({
All of the database queries above should be combined into a single one.

2021-01-11 08:31 UTC, Skn0tt commented on app/time-utils/format.ts
> +export function getDateHumanFormat(date: Date): { dateString: string; timeString: string } {
`date-fns` offers a function that does exactly this: https://date-fns.org/v2.16.1/docs/format

2021-01-11 08:33 UTC, Skn0tt commented
> Currently pipeline is not running to as the test ist not passing in the ci. I really don't understand why, locally its working as expected. I tried debugging it but cannot find the mistake. Maybe someone could take a look at this please

It looks like the Baïkal instance doesn't have write access to it's database during CI. I'll take a look.

2021-01-11 08:48 UTC, Skn0tt requested changes

2021-01-11 08:48 UTC, Skn0tt commented on app/caldav/index.ts
> +  return response
I don't think we should return the full-blown `response` here, but rather some Kalle-Internal representation of it, to prevent spilling CalDav-response-interna over the rest of the codebase.

2021-01-11 09:01 UTC, Skn0tt commented on app/caldav/index.ts
> +  timezone: number
Is there a reason for this parameter to go unused?

2021-01-11 09:22 UTC, Skn0tt commented
> Currently pipeline is not running to as the test ist not passing in the ci. I really don't understand why, locally its working as expected. I tried debugging it but cannot find the mistake. Maybe someone could take a look at this please

See #110.

2021-01-11 11:47 UTC, rohansaw commented on app/caldav/index.ts
> +  return response
I now only return the statusMessage, as i guess this is sufficient to work with if needed. The only case we would net to use this is to handle errors

2021-01-11 11:54 UTC, rohansaw commented on app/meetings/pages/meeting/bookings/[meetingId].tsx
> +    return <Skeleton count={10} />
Not quite sure why we need that? :thinking:

2021-01-11 11:56 UTC, rohansaw commented on app/appointments/mutations/bookAppointment.ts
> +      auth: { username: calendar.username, password, digest: true },
Added a new Issue for this, as this needs to be changed in multiple places.
https://github.com/kalle-app/kalle/issues/111

2021-01-11 16:36 UTC, rohansaw commented on app/caldav/index.ts
> +  timezone: number
I wanted to use this at the begging but then realized that I have no Idea on how to use it yet and would have to dive deeper into timezones first. Therefore currently we only use `Europe/Berlin` as Timezone for all created events.

We will need to change this, but I am not quite sure if we can just add the Timezone-offset to the date we want to save. Do you have any ideas on this?

2021-01-11 16:46 UTC, Skn0tt commented on app/caldav/index.ts
> +  timezone: number
Maybe this could be helpful? https://tools.ietf.org/html/rfc2445#section-4.6.5

2021-01-11 17:30 UTC, rohansaw commented on app/caldav/index.ts
> +  timezone: number
Yeah, I also had a look at this before but the problem is that we only have the Timezone-offset from the meeting (e.g 1,5 for a offset of 1,5hours from GMT). But for the VTimezone section we need a timezoneID but offset->timezoneID is not bijective, so we cannot create a unambiguously timezoneID from the offset. 
I tried creating a VTimezone section but didn't get it working yet.

Thats why I thought it might make sense, to first use a fixed timezone and then we might have to generally think more about how we work with timezones as we probably need to take into consideration the location of users.

2021-01-11 18:42 UTC, Skn0tt commented on app/caldav/index.ts
> +  timezone: number
Makes sense 👍🏻

2021-01-12 11:44 UTC, Skn0tt requested changes

2021-01-12 11:44 UTC, Skn0tt commented on app/caldav/index.ts
> +  return response.res.statusMessage
```suggestion
  return response.res.statusMessage === "Created" ? "success" : "failure"
```
The exact value of `statusMessage` is an implementation detail local to this function and could potentially differ between CalDav implementations.
Thus, the evaluation of wether a request was successful or not should be performed by _this_ function, and not by the caller.

2021-01-12 12:59 UTC, rohansaw commented on app/caldav/index.ts
> +  return response.res.statusMessage
makes sense :+1:

2021-01-12 13:47 UTC, Skn0tt approved these changes

2021-01-12 13:53 UTC, merged