Feature/gh 70 #2
kalle-app/kalle pull request #107
Opened 2021-01-10 09:06 UTC by Lasklu

Add a connection to google calendar.

- [ ] connect a calendar
- [ ] get free busy
- [ ] create Event

Missing

- we have to map the freebusy response to our format (at create event this is already done)
- we have to remove some code in "appointments", cause this was changed due testing

2021-01-10 09:06 UTC, Lasklu commented
@rohansaw

2021-01-26 12:08 UTC, Skn0tt requested changes
I've looked through half of the PR now. Please review your code yourself first, and ping me once you think it's ready to present.

2021-01-26 12:08 UTC, Skn0tt commented on app/googlecalendar/queries/createCalendarEvent.ts
> +interface Props {
```suggestion
interface CreateCalendarArguments {
```

2021-01-26 12:08 UTC, Skn0tt commented on app/googlecalendar/queries/createCalendarEvent.ts
> +  calendar.events.insert(
This should be awaited.

2021-01-26 12:08 UTC, Skn0tt commented on app/googlecalendar/queries/createCalendarEvent.ts
> +export default async function createCalendarEvents({ appointment, userId }: Props) {
It's called createCalendarEvent*s*, but it creates only a single event. Am I missing smth?

2021-01-26 12:08 UTC, Skn0tt commented on app/googlecalendar/queries/createCalendarEvent.ts
> +  var event = {
Please use `let`/`const` instead of `var`.

2021-01-26 12:08 UTC, Skn0tt commented on app/googlecalendar/queries/createCalendarEvent.ts
> +  let startDate: Date = new Date(appointment.start)
```suggestion
  let startDate = new Date(appointment.start)
```

2021-01-26 12:08 UTC, Skn0tt commented on app/googlecalendar/queries/createCalendarEvent.ts
> +        console.log("There was an error contacting the Calendar service: " + err)
We shouldn't swallow errors here, but throw them.

2021-01-26 12:08 UTC, Skn0tt commented on app/googlecalendar/queries/createConnection.ts
> +export default async function getCalendars() {
```suggestion
export default async function get<WhatKindOfConnectionIsThis?>Connection() {
```

2021-01-26 12:08 UTC, Skn0tt commented on app/googlecalendar/queries/getFreeBusySchedule.ts
> +interface Props {
```suggestion
interface GetFreeBusyScheduleArgs {
```

2021-01-26 12:08 UTC, Skn0tt commented on app/googlecalendar/queries/getFreeBusySchedule.ts
> +interface DateTimeString {
If it's a DateTime, why does it have `start` and `end`? Shouldn't this be called "Interval" or smth instead?

2021-01-26 23:05 UTC, rohansaw requested changes

2021-01-26 23:05 UTC, rohansaw commented on app/googlecalendar/queries/getFreeBusySchedule.ts
> +  return calendar.freebusy
Why do you return here? The function is called getFreeBusySchedule, so we probably should await the quere get its result and then return accordingly

2021-01-26 23:05 UTC, rohansaw commented on app/googlecalendar/queries/getFreeBusySchedule.ts
> +  arr.push({ start: 16754814600, end: 16754818200 })
magic numbers, pls at least add a comment what they are

2021-01-26 23:05 UTC, rohansaw commented on app/users/pages/settings.tsx
> +  // TODO: use CalendarCredentials for CalDav as well
Has this happend already? If not so - create a issue for this or fix this before merging pls

2021-01-26 23:05 UTC, rohansaw commented on cypress/integration/CalendarSpecs/googleCalendar.spec.ts
> +// TODO Manage Social Login, see https://github.com/lirantal/cypress-social-logins/issues/78
This doesn't seem to be ready?

2021-01-27 09:50 UTC, Skn0tt commented on app/googlecalendar/queries/getFreeBusySchedule.ts
> +  arr.push({ start: 16754814600, end: 16754818200 })
Or even better: Assign them to constants that describe their meaning

2021-01-27 17:27 UTC, phlprcks commented on app/googlecalendar/helpers/updateCalendarCredentials.ts
> +  if (!credentials) return null
It's expected, bc Google has different credentials than other calendars. Caldav has some null values where Google Calendars do have credentials

2021-01-27 17:44 UTC, phlprcks commented on app/googlecalendar/pages/oauth2Callback.tsx
> +function OAuthCallbackPage() {
indeed!

2021-01-27 18:07 UTC, phlprcks commented on app/googlecalendar/queries/createCalendarEvent.ts
> +export default async function createCalendarEvents({ appointment, userId }: Props) {
No, in the end that was not even used anymore... historically grown 😅

2021-01-27 21:13 UTC, phlprcks commented on app/appointments/queries/getTimeSlots.ts
> +  takenTimeSlots.push(...(await getGoogleCalendarSlots(calendars, meeting, meetingOwner)))
wasn't aware of this! Great, thanks

2021-02-03 16:42 UTC, Skn0tt commented on app/appointments/queries/getTimeSlots.ts
> +    // eslint-disable-next-line array-callback-return
Maybe we should use .forEach instead.

2021-02-03 20:40 UTC, merged