Feature/145 design improvements
kalle-app/kalle pull request #150
Opened 2021-02-08 16:11 UTC by rohansaw

Closes: #145 

- [ ] Redesigned Meetings overview
- [ ] Redone menu structure
- [ ] Fixed typos on home screen
- [ ] Refactored Dashboard Design
- [ ] Display upcoming appointments on Dashboards
- [ ] Outsourced calendars to own menu item

2021-02-12 08:33 UTC, rohansaw commented
@phlprcks

2021-02-12 11:44 UTC, phlprcks requested changes

2021-02-12 11:44 UTC, phlprcks commented on app/pages/index.tsx
> +    <section style={{ minHeight: "70vh" }}>
could you add a grid here (just like on the /meetings page) to align the heights of the meetings and bookings boxes?

2021-02-12 11:44 UTC, phlprcks commented on app/appointments/components/availableTimeSlotsSelection.tsx
> +          if (slot.start > new Date()) {
this has the effect that i cannot book a time slot that is today in the future, it just blocks the whole day...

2021-02-12 11:44 UTC, phlprcks commented on app/appointments/components/availableTimeSlotsSelection.tsx
> +          if (slot.start > new Date()) {
is not directly related to the styling so feel free to open an issue for this if you dont want to fix it right away ;)

2021-02-12 11:44 UTC, phlprcks commented on app/meetings/pages/meetings.tsx
> +            <Button variant="primary">Create new Meeting</Button>
any ideas how this change might have an impact on #158 ? I have never seen this bug before but are not sure if it is caused by this.

2021-02-12 11:47 UTC, phlprcks commented
also please resolve merge changes @rohansaw 😃

2021-02-14 12:54 UTC, rohansaw commented on app/meetings/pages/meetings.tsx
> +            <Button variant="primary">Create new Meeting</Button>
I actually dont have this bug, so dont know :/

2021-02-14 13:04 UTC, rohansaw commented on app/appointments/components/availableTimeSlotsSelection.tsx
> +          if (slot.start > new Date()) {
Did you try this and see this problem?
This should acutally not happen, i didn't have that problem and also don't know why it would exist :sweat_smile:

2021-02-14 14:02 UTC, phlprcks commented on app/appointments/components/availableTimeSlotsSelection.tsx
> +          if (slot.start > new Date()) {
nvm. Couldn't reproduce that incident. Might have been sth different (e.g. blocked date in the connected calendar or sth that made me think this bug exists...)

2021-02-14 14:08 UTC, phlprcks approved these changes

2021-02-14 14:09 UTC, merged