Input validation
kalle-app/kalle pull request #161
Opened 2021-02-16 11:02 UTC by sspangenberg

Closes: #77

2021-02-16 13:56 UTC, sspangenberg commented on app/meetings/components/schedules/AddScheduleModal.tsx
> +          result = false
Done

2021-02-18 10:00 UTC, sspangenberg commented
@phlprcks please check whether the validation of schedule times work as expected

2021-02-18 10:37 UTC, phlprcks requested changes
how about validating the input when users book a meeting from the schedule link? I have some provisional logic for that in #165 but it would make sense to use zod for this validation as well 👍

2021-02-18 10:37 UTC, phlprcks commented on app/auth/validations.ts
> +  end: z.string(),
Looks great, but one check is missing: I can enter 23:00 - 17:00. The first time should be before the 2nd one, right? 🤔 

Also, as discussed in (#153 ) that we should adapt to user preferences in time format, that's why I created #167 . We would need a different validation logic once that is implemented, but that can be part of #167 in my opinion.

2021-02-18 10:37 UTC, phlprcks commented on app/meetings/components/schedules/AddScheduleModal.tsx
> +      message: "Please check the entered times",
```suggestion
      message: "Please check the entered times. Expected is a format of hour:minutes, e.g. 09:30",
```

2021-02-18 10:37 UTC, phlprcks commented on app/meetings/components/schedules/AddScheduleModal.tsx
> +              return true
see above

2021-02-18 12:19 UTC, sspangenberg commented on app/auth/validations.ts
> +  end: z.string(),
I agree that all time format related tasks should be part of #167. The time comparison is implemented in the latest commit.

2021-02-18 12:25 UTC, sspangenberg commented
> 
> 
> how about validating the input when users book a meeting from the schedule link? I have some provisional logic for that in #165 but it would make sense to use zod for this validation as well 👍

 If you have aready worked on it I would implement it on your branch due to simplicity

2021-02-18 13:38 UTC, phlprcks approved these changes

2021-02-18 13:38 UTC, merged