Delete schedule presets
kalle-app/kalle pull request #177
Opened 2021-02-22 11:10 UTC by sspangenberg

Closes: #118

2021-02-22 15:32 UTC, phlprcks requested changes

2021-02-22 15:32 UTC, phlprcks commented on app/meetings/components/schedules/AllSchedules.tsx
> +      setMessage("There are still meetings with this schedule")
there is some little bug: I have multiple schedules. Now I try to delete one that causes this error message correctly. However, the error message is displayed in all the meetings, not just the one I am trying to delete

2021-02-23 08:30 UTC, sspangenberg commented on app/meetings/components/schedules/AllSchedules.tsx
> +      setMessage("There are still meetings with this schedule")
Should be fixed

2021-02-23 15:06 UTC, phlprcks approved these changes

2021-02-23 15:06 UTC, merged