Feature/invite mails
kalle-app/kalle pull request #36
Opened 2020-11-26 16:51 UTC by Lasklu

closes #23

2020-11-27 08:34 UTC, Skn0tt commented on README.md
> +# Setup
Good idea to adapt our README!

2020-11-27 08:34 UTC, Skn0tt commented on README.md
> +EMAIL_FROM="email_address" //email-domain which will be used for email shipping
```suggestion
EMAIL_FROM="changeme@yourdomain.com"
```
For brevity's sake.

2020-11-27 08:34 UTC, Skn0tt commented on app/components/createEmail/EmailFactory.tsx
> +  private transporter: any
Try not to use the `any` type to fully benefit from the good things typescript brings.

2020-11-27 08:34 UTC, Skn0tt commented on app/components/createEmail/emailCollection/emailConfirmation.tsx
> +  sendEmail() {
Why override this when you simply call super?

2020-11-27 08:34 UTC, Skn0tt commented on app/components/createEmail/emailCollection/emailConfirmation.tsx
> +  constructor(appointment) {
This is not type-safe at all. Think about defining an interface for appointments.

2020-11-27 08:34 UTC, Skn0tt commented on app/components/createEmail/EmailFactory.tsx
> +export default abstract class EmailFactory {
Which features are planned for the email factory that require using class hierarchy? The way it is at the moment, the task at hand could be achieved much simpler using a couple of functions that call each other.

2020-11-27 08:34 UTC, Skn0tt commented on app/components/createEmail/helper/createCalendarEvent.tsx
> +export function createCalendarEvent(appointment) {
Again: not type-safe

2020-11-27 08:34 UTC, Skn0tt commented on app/components/createEmail/helper/createSMTPConnection.tsx
> +  verifyConnection(transporter)
This won't do anything except logging to STDERR. Maybe you can use Promises and async/await to make this blocking.

(also: do we really wanna check every single SMTP connection we create? having it crash during sending the e-mail wouldn't be that much worse I guess)

2020-11-27 08:34 UTC, Skn0tt commented on app/components/createEmail/queries/sendMail.tsx
> +    email = new EmailConfirmation(properties.appointment)
maybe create multiple queries instead of switching through the types in one queries

2020-11-27 08:34 UTC, Skn0tt commented on package.json
> +    "ics": "2.26.1",
#30 uses `node-ics`, maybe we can decide on one of them.

2020-12-03 08:12 UTC, Skn0tt requested changes

2020-12-03 08:12 UTC, Skn0tt commented on app/components/createEmail/helper/createCalendarEvent.tsx
> +  ics.createEvent(event, (error, value) => {
Have you tested this? Callbacks are normally a sign of asynchronous execution, which would break given this function doesn't wait for the execution to happen.

2020-12-03 08:12 UTC, Skn0tt commented on app/components/createEmail/helper/emailHelper.tsx
> +function checkIfSMTPEnvVariablesExist(): void {
Nice sanity check!

2020-12-03 08:12 UTC, Skn0tt commented on app/components/createEmail/helper/emailHelper.tsx
> +    secure: false, //TODO upgrade later with STARTTLS
Why don't we enable that already / make it configurable via env vars?

2020-12-03 08:12 UTC, Skn0tt commented on app/components/createEmail/helper/emailHelper.tsx
> +    send: process.env.MODE !== "development",
What will happen with mail sent in development? Will it be printed to the console? (couldn't find anything about that in the docs)

2020-12-03 08:12 UTC, Skn0tt commented on app/components/createEmail/helper/emailHelper.tsx
> +export function sendEmail(): Email {
That name irritated me a bit. Maybe rename to `createEmail`, `getEmailService` or `getEmailFacade`?

I also think we should make this a singleton. Don't want a ton of email instances floating around our code, right?

2020-12-03 08:12 UTC, Skn0tt commented on app/components/createEmail/helper/emailHelper.tsx
> +function createSMTPConnection(): nodemailer.Transporter {
This should also be a singleton, as we don't want multiple open SMTP connections.

2020-12-03 08:12 UTC, Skn0tt commented on app/components/createEmail/queries/sendConfirmationMail.tsx
> +function buildConfirmationMail(email: Email, appointment: appointment): void {
Feels like a misnomer to me. It also *sends* the email, so why is it called *build*?

2020-12-03 08:12 UTC, Skn0tt commented on app/components/createEmail/types.tsx
> +export interface appointment {
Typescript convention: Types are named in PascalCase.

```suggestion
export interface Appointment {
```

2020-12-04 15:25 UTC, Lasklu commented on app/components/createEmail/helper/emailHelper.tsx
> +    send: process.env.MODE !== "development",
it will open a new tab with the email infos in it. So we can check the content but I do not see the need to send it each time

2020-12-05 22:40 UTC, Lasklu commented on app/components/createEmail/helper/createCalendarEvent.tsx
> +  ics.createEvent(event, (error, value) => {
yes of course tested it, seems to be a synchronus method with a callback

2020-12-05 22:43 UTC, Lasklu commented on app/components/createEmail/helper/emailHelper.tsx
> +    secure: false, //TODO upgrade later with STARTTLS
did not work for me (but tried only 10min, so we should find a fix) because of presentation reasons, I would delay, but see #50

2020-12-05 22:43 UTC, Lasklu commented on app/components/createEmail/helper/emailHelper.tsx
> +export function sendEmail(): Email {
renamed it. and made as singleton

2020-12-05 22:59 UTC, merged