Refactor component folder
kalle-app/kalle pull request #94
Opened 2020-12-27 14:29 UTC by Skn0tt

This PR contains some refactorings for files that used to be in the `components` folder.
It is recommended to review this PR commit-by-commit.

2020-12-27 16:06 UTC, rohansaw commented on app/appointments/utils/createCalendarEvent.ts
> +    location: appointment.location,
This currently is an optional attribute. I am not sure wheater it was exactly this issue, but I think the sending of emails did not work properly if an appointment does not contain a location and/or description. Did you test this?

2020-12-27 16:12 UTC, Skn0tt commented on app/appointments/utils/createCalendarEvent.ts
> +    location: appointment.location,
No, I did not test this, as I didn't do anything non-trivial. AFAICT, this PR does not change anything in regard to `location` - so if it's broke, it should've already been broke before.

2020-12-27 17:35 UTC, rohansaw commented on app/appointments/utils/createCalendarEvent.ts
> +    location: appointment.location,
I think it was hardcoded before, but maybe @Lasklu knows more about this, as it was his branch :sweat_smile:

2020-12-27 17:48 UTC, Lasklu commented on app/appointments/utils/createCalendarEvent.ts
> +    location: appointment.location,
I am currently checking it
I think this might be a problem, but I need some more minutes :D

2020-12-27 18:17 UTC, Lasklu commented on app/appointments/utils/createCalendarEvent.ts
> +    location: appointment.location,
Ok this works fine, I tested it. Location and further params are also defined as optional in the type definition of ics

2020-12-27 18:36 UTC, Lasklu requested changes

2020-12-27 18:36 UTC, Lasklu commented on app/appointments/utils/createCalendarEvent.ts
> +      appointment.start.getDay(),
getDay only returns the day of a week ([link](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Date/getDay)) which might be 0.
```suggestion
      appointment.start.getDate(),
```

2020-12-27 18:36 UTC, Lasklu commented on app/appointments/pages/schedule/[uid]/[slug].tsx
> +  const [sendConfirmationMail] = useMutation(sendConfirmationMailMutation)
I do not know how to use useMutation exactly but whenever I used it (I think I used it the wrong way), it got called several times. This means that even the mail was sent several times. I just want to make sure that this will not happen?

2020-12-27 18:36 UTC, Lasklu commented on utils/checkEnvVariables.tsx
> +export function checkEnvVariables(...names: string[]) {
nice!

2020-12-27 18:36 UTC, Lasklu commented on app/email.ts
> +  checkEnvVariables("SMTP_HOST", "SMTP_PORT", "SMTP_USER", "SMTP_PASSWORD", "EMAIL_FROM", "MODE")
if this is finally a (beautiful) one-liner: Why don't we call it directly?

2020-12-27 21:32 UTC, Skn0tt commented on app/appointments/utils/createCalendarEvent.ts
> +      appointment.start.getDay(),
Good catch!

2020-12-27 21:33 UTC, Skn0tt commented on app/appointments/pages/schedule/[uid]/[slug].tsx
> +  const [sendConfirmationMail] = useMutation(sendConfirmationMailMutation)
Do you have a code example of when it was invoked several times?

2020-12-27 21:33 UTC, Skn0tt commented on app/email.ts
> +  checkEnvVariables("SMTP_HOST", "SMTP_PORT", "SMTP_USER", "SMTP_PASSWORD", "EMAIL_FROM", "MODE")
Good idea!

2020-12-28 09:14 UTC, Skn0tt commented on app/appointments/pages/schedule/[uid]/[slug].tsx
> +  const [sendConfirmationMail] = useMutation(sendConfirmationMailMutation)
Could it be that you used a `query` instead of a `mutation`? Queries can be refetched every couple of seconds to keep the data up-to-date.

2020-12-28 09:49 UTC, Lasklu commented on app/appointments/pages/schedule/[uid]/[slug].tsx
> +  const [sendConfirmationMail] = useMutation(sendConfirmationMailMutation)
ouh yes, that's true, I used query..:D

2020-12-28 09:50 UTC, Lasklu approved these changes

2020-12-28 12:19 UTC, merged